service: service-07-dynamodb
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

# you can add statements to the Lambda function's IAM Role here
#  iam:
#    role:
#      statements:
#        - Effect: "Allow"
#          Action:
#            - "s3:ListBucket"
#          Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#        - Effect: "Allow"
#          Action:
#            - "s3:PutObject"
#          Resource:
#            Fn::Join:
#              - ""
#              - - "arn:aws:s3:::"
#                - "Ref" : "ServerlessDeploymentBucket"
#                - "/*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  patterns:
#    - '!exclude-me.js'
#    - '!exclude-me-dir/**'
#    - include-me.js
#    - include-me-dir/**

functions:
  getUser:
    handler: handler.getUser
    events:
      - httpApi:
          path: /{userId}
          method: get
  updateUser:
    handler: handler.updateUser
    events:
      - httpApi:
          path: /{userId}
          method: put
  createUser:
    handler: handler.createUser
    events:
      - httpApi:
          path: /
          method: post
  deleteUser:
    handler: handler.deleteUser
    events:
      - httpApi:
          path: /{userId}
          method: delete
  updateUserRewards:
    handler: handler.updateUserRewards
    events:
      - httpApi:
          path: /{userId}/rewards
          method: put
